# Generated by Django 5.0.6 on 2024-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_student_date_of_birth_student_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gallery',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
